version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - CONNECT4_CONFIG=configs/h6_w7_c4_small_600.yaml
      - CONNECT4_CHECKPOINT=model_ckpts/cc4_current_net__iter7.pth.tar
    volumes:
      - ./configs:/app/configs
      - ./model_ckpts:/app/model_ckpts
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8001
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - redis
    restart: unless-stopped

volumes:
  redis_data: 