board:
  num_rows: 5
  num_cols: 5
  win_streak: 3

mcts:
  num_simulations: 800
  temperature_MCTS: 1.1

self_play:
  num_games_per_MCTS_process: 256
  num_evaluator_games: 64
  MCTS_num_processes: 8

model:
  num_blocks: 5

training:
  max_train_steps: 50000
  iterate_steps: 2000
  neural_net_name: "h5_w5_c3_current_net_small"
  d0: 0.00001
  batch_size: 64
  max_norm: 1.0
