board:
  num_rows: 5
  num_cols: 5
  win_streak: 3

mcts:
  num_simulations: 800
  temperature_MCTS: 0.8
  initial_move_count: 5

self_play:
  num_games_per_MCTS_process: 256
  num_evaluator_games: 64
  MCTS_num_processes: 8

model:
  num_blocks: 10

training:
  max_train_steps: 50000
  iterate_steps: 5000
  neural_net_name: "h5_w5_c3_current_net_medium"
  d0: 0.00001
  batch_size: 64
  max_norm: 1.0
