board:
  num_cols: 5
  num_rows: 5
  win_streak: 3
mcts:
  initial_move_count: 5
  num_simulations: 200
  temperature_MCTS: 1.0
model:
  num_blocks: 5
self_play:
  MCTS_num_processes: 8
  batch_size: 8
  c_puct: 2.5
  num_evaluator_games: 128
  num_games: 1024
training:
  batch_size: 64
  d0: 1.0e-05
  iterate_steps: 20000
  max_norm: 1.0
  max_train_steps: 100000
  neural_net_name: h5_w5_c3_current_net_small
