board:
  num_cols: 7
  num_rows: 6
  win_streak: 4
mcts:
  initial_move_count: 10
  num_simulations: 200
  temperature_MCTS: 1.0
model:
  num_blocks: 20
self_play:
  MCTS_num_processes: 8
  batch_size: 4
  c_puct: 2.5
  num_evaluator_games: 128
  num_games: 4096
training:
  batch_size: 64
  d0: 1.0e-05
  iterate_steps: 20000
  max_norm: 1.0
  max_train_steps: 100000
  neural_net_name: h6_w7_c4_current_net_large
