board:
  num_cols: 7
  num_rows: 6
  win_streak: 4
mcts:
  initial_move_count: 10
  num_simulations: 800
  temperature_MCTS: 1.0
model:
  num_blocks: 19
self_play:
  MCTS_num_processes: 16
  batch_size: 4
  c_puct: 2.5
  num_evaluator_games: 8
  num_games_per_MCTS_process: 64
training:
  batch_size: 1024
  d0: 1.0e-05
  iterate_steps: 2000
  max_norm: 1.0
  max_train_steps: 10000
  neural_net_name: h6_w7_c4_current_net_base
