board:
  num_rows: 6
  num_cols: 7
  win_streak: 4

mcts:
  num_simulations: 600
  temperature_MCTS: 0.8
  initial_move_count: 5

self_play:
  num_games_per_MCTS_process: 256
  num_evaluator_games: 64
  MCTS_num_processes: 8

model:
  num_blocks: 5

training:
  max_train_steps: 50000
  iterate_steps: 5000
  neural_net_name: "h6_w7_c4_current_net_small_600"
  d0: 0.00001
  batch_size: 64
  max_norm: 1.0