board:
  num_rows: 6
  num_cols: 7
  win_streak: 4

mcts:
  num_simulations: 400
  temperature_MCTS: 1.1

self_play:
  num_games_per_MCTS_process: 64
  num_evaluator_games: 64
  MCTS_num_processes: 1

model:
  num_blocks: 5

training:
  neural_net_name: "cc4_current_net_small"
  batch_size: 1024
  num_epochs: 300
  lr: 0.001
  gradient_acc_steps: 1
  max_norm: 1.0
