board:
  num_rows: 9
  num_cols: 9
  win_streak: 5

mcts:
  num_simulations: 800
  temperature_MCTS: 1.1
  initial_move_count: 10

self_play:
  num_games_per_MCTS_process: 512
  num_evaluator_games: 64
  MCTS_num_processes: 8

model:
  num_blocks: 20

training:
  max_train_steps: 50000
  iterate_steps: 5000
  neural_net_name: "h9_w9_c5_current_net_large"
  d0: 0.00001
  batch_size: 64
  max_norm: 1.0